using EnterpriseApp.Domain.Common;
using EnterpriseApp.Domain.DomainEvents.Authorization;
using EnterpriseApp.Domain.Exceptions;

namespace EnterpriseApp.Domain.Entities.Authorization;

/// <summary>
/// A named bundle of permissions assignable to users. Optionally hierarchical
/// (<see cref="ParentRoleId"/>) so child roles inherit parent permissions.
/// <para>Honours the legacy NHCS pattern of caching a JWT-encoded permission snapshot,
/// but moves it from the abused <c>IdentityRole.ConcurrencyStamp</c> to a dedicated
/// <see cref="PermissionsSnapshot"/> field. See <c>.claude/rules/authorization.md §4</c>.</para>
/// </summary>
public sealed class Role : AuditableEntity<RoleId>
{
    private readonly List<RolePermission> _rolePermissions = [];

    private Role() : base(RoleId.New()) { }

    public static Role Create(
        string  name,
        string  normalizedName,
        string? description,
        Guid?   tenantId,
        RoleId? parentRoleId,
        bool    isSystem,
        string? createdBy)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentException.ThrowIfNullOrWhiteSpace(normalizedName);

        var role = new Role
        {
            Name           = name.Trim(),
            NormalizedName = normalizedName.Trim().ToUpperInvariant(),
            Description    = description?.Trim(),
            TenantId       = tenantId,
            ParentRoleId   = parentRoleId,
            IsSystem       = isSystem,
            CreatedBy      = createdBy,
        };
        role.RaiseDomainEvent(new RoleCreated(role.Id, role.Name, tenantId, createdBy));
        return role;
    }

    public string  Name           { get; private set; } = string.Empty;
    public string  NormalizedName { get; private set; } = string.Empty;
    public string? Description    { get; private set; }
    public Guid?   TenantId       { get; private set; }
    public RoleId? ParentRoleId   { get; private set; }

    /// <summary>System roles (e.g. <c>super-admin</c>) cannot be deleted or renamed.</summary>
    public bool IsSystem { get; private set; }

    /// <summary>
    /// Signed JWT snapshot of the resolved permissions for this role.
    /// Replaces NHCS' abuse of <c>ConcurrencyStamp</c> for the same purpose.
    /// Regenerated by Application after grant/revoke and dispatched in
    /// <see cref="DomainEvents.Authorization.RolePermissionsChanged"/>.
    /// </summary>
    public string? PermissionsSnapshot           { get; private set; }
    public DateTimeOffset? PermissionsSnapshotUpdatedAt { get; private set; }

    public IReadOnlyCollection<RolePermission> RolePermissions => _rolePermissions.AsReadOnly();

    // ── Behaviour ────────────────────────────────────────────────────────────

    public void Rename(string name, string? updatedBy)
    {
        if (IsSystem) throw new DomainException("System roles cannot be renamed.");
        ArgumentException.ThrowIfNullOrWhiteSpace(name);

        Name           = name.Trim();
        NormalizedName = Name.ToUpperInvariant();
        UpdatedBy      = updatedBy;
        UpdatedAt      = DateTimeOffset.UtcNow;
    }

    public void UpdateDescription(string? description, string? updatedBy)
    {
        Description = description?.Trim();
        UpdatedBy   = updatedBy;
        UpdatedAt   = DateTimeOffset.UtcNow;
    }

    public void GrantPermission(Permission permission, string grantedBy, DateTimeOffset? expiresAt = null)
    {
        ArgumentNullException.ThrowIfNull(permission);

        if (_rolePermissions.Any(rp => rp.PermissionId == permission.Id))
            throw new DomainException(
                $"Role '{Name}' already has permission '{permission.Code}'.");

        if (permission.TenantId is not null && permission.TenantId != TenantId)
            throw new DomainException(
                $"Cannot grant permission '{permission.Code}' from a different tenant.");

        var rp = RolePermission.Create(Id, permission.Id, grantedBy, expiresAt);
        _rolePermissions.Add(rp);

        RaiseDomainEvent(new PermissionGranted(
            RoleId:         Id,
            PermissionId:   permission.Id,
            PermissionCode: permission.Code.Value,
            GrantedBy:      grantedBy,
            TenantId:       TenantId));
        RaiseDomainEvent(new RolePermissionsChanged(Id, TenantId));
    }

    public void RevokePermission(PermissionId permissionId, string revokedBy)
    {
        var rp = _rolePermissions.FirstOrDefault(x => x.PermissionId == permissionId)
            ?? throw new DomainException(
                $"Role '{Name}' does not have the requested permission.");

        _rolePermissions.Remove(rp);

        RaiseDomainEvent(new PermissionRevoked(
            RoleId:       Id,
            PermissionId: permissionId,
            RevokedBy:    revokedBy,
            TenantId:     TenantId));
        RaiseDomainEvent(new RolePermissionsChanged(Id, TenantId));
    }

    /// <summary>
    /// Updates the cached <see cref="PermissionsSnapshot"/>. Called by Application after
    /// resolving and signing the JWT containing the role's full permission set.
    /// </summary>
    public void RefreshPermissionsSnapshot(string signedSnapshot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(signedSnapshot);
        PermissionsSnapshot           = signedSnapshot;
        PermissionsSnapshotUpdatedAt  = DateTimeOffset.UtcNow;
    }

    public void Delete(string? deletedBy)
    {
        if (IsSystem) throw new DomainException("System roles cannot be deleted.");
        SoftDelete(deletedBy);
        RaiseDomainEvent(new RoleDeleted(Id, Name, deletedBy));
    }
}

/// <summary>Strongly-typed Id for <see cref="Role"/>.</summary>
public sealed record RoleId(Guid Value)
{
    public static RoleId New()             => new(Guid.NewGuid());
    public static RoleId From(Guid value)  => new(value);
    public override string ToString()      => Value.ToString();
}
